<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MESTOP.Core\MESTOP.Core.csproj" />
    <ProjectReference Include="..\MESTOP.Entity\MESTOP.Entity.csproj" />
  </ItemGroup>

</Project>
